// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://api.acme.example/v1' | 'https://api.staging.acme.example/v1' | (string & {});
};

/**
 * Where the ticket sits in the support workflow.
 */
export type TicketStatus = 'open' | 'waiting' | 'closed';

/**
 * How badly the requester wants this handled.
 */
export type TicketPriority = 'low' | 'normal' | 'high';

export type Ticket = {
  /**
   * Server-assigned identifier.
   */
  id: number;
  /**
   * One-line summary of the problem.
   */
  subject: string;
  status: TicketStatus;
  /**
   * When the ticket was opened, in UTC.
   */
  openedOn: string;
  priority: TicketPriority;
  /**
   * Username of the agent who owns this ticket, or null if unassigned.
   */
  assignedTo: string | null;
};

export type TicketList = {
  data: Array<Ticket>;
  page: number;
  pageSize: number;
  /**
   * Total number of tickets matching the filter.
   */
  total: number;
};

export type CreateTicketRequest = {
  subject: string;
  priority?: TicketPriority;
  /**
   * Optional. Leave off to drop the ticket in the unassigned queue.
   */
  assignedTo?: string | null;
};

export type ApiError = {
  code: string;
  message: string;
  /**
   * Per-field problems, when the failure was a validation failure.
   */
  details?: Array<{
    field: string;
    issue: string;
  }>;
};

export type ListTicketsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Only return tickets in this status.
     */
    status?: TicketStatus;
    /**
     * Filter by the assignee's username. Omit for all tickets.
     */
    assignedTo?: string;
    page?: number;
    pageSize?: number;
  };
  url: '/tickets';
};

export type ListTicketsErrors = {
  /**
   * The request could not be understood.
   */
  400: ApiError;
};

export type ListTicketsError = ListTicketsErrors[keyof ListTicketsErrors];

export type ListTicketsResponses = {
  /**
   * A page of tickets.
   */
  200: TicketList;
};

export type ListTicketsResponse = ListTicketsResponses[keyof ListTicketsResponses];

export type GetTicketByIdData = {
  body?: never;
  path: {
    /**
     * The numeric ticket id.
     */
    id: number;
  };
  query?: never;
  url: '/ticket/{id}';
};

export type GetTicketByIdErrors = {
  /**
   * No ticket with that id exists.
   */
  404: ApiError;
};

export type GetTicketByIdError = GetTicketByIdErrors[keyof GetTicketByIdErrors];

export type GetTicketByIdResponses = {
  /**
   * The requested ticket.
   */
  200: Ticket;
};

export type GetTicketByIdResponse = GetTicketByIdResponses[keyof GetTicketByIdResponses];

export type CreateTicketData = {
  body: CreateTicketRequest;
  path?: never;
  query?: never;
  url: '/ticket';
};

export type CreateTicketErrors = {
  /**
   * The request could not be understood.
   */
  400: ApiError;
  /**
   * The body was well-formed but failed validation.
   */
  422: ApiError;
};

export type CreateTicketError = CreateTicketErrors[keyof CreateTicketErrors];

export type CreateTicketResponses = {
  /**
   * The newly created ticket.
   */
  201: Ticket;
};

export type CreateTicketResponse = CreateTicketResponses[keyof CreateTicketResponses];
