// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Where the ticket sits in the support workflow.
 */
export const zTicketStatus = z.enum(['open', 'waiting', 'closed']);

/**
 * How badly the requester wants this handled.
 */
export const zTicketPriority = z.enum(['low', 'normal', 'high']);

export const zTicket = z.object({
  id: z
    .int()
    .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  subject: z.string().min(1).max(120),
  status: zTicketStatus,
  openedOn: z.iso.datetime(),
  priority: zTicketPriority,
  assignedTo: z.string().nullable(),
});

export const zTicketList = z.object({
  data: z.array(zTicket),
  page: z
    .int()
    .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  pageSize: z
    .int()
    .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  total: z
    .int()
    .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
});

export const zCreateTicketRequest = z.object({
  subject: z.string().min(1).max(120),
  priority: zTicketPriority.optional(),
  assignedTo: z.string().nullish(),
});

export const zApiError = z.object({
  code: z.string(),
  message: z.string(),
  details: z
    .array(
      z.object({
        field: z.string(),
        issue: z.string(),
      }),
    )
    .optional(),
});

export const zListTicketsQuery = z.object({
  status: zTicketStatus.optional(),
  assignedTo: z.string().optional(),
  page: z
    .int()
    .gte(1)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional()
    .default(1),
  pageSize: z.int().gte(1).lte(100).optional().default(25),
});

/**
 * A page of tickets.
 */
export const zListTicketsResponse = zTicketList;

export const zGetTicketByIdPath = z.object({
  id: z
    .int()
    .gte(1)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
});

/**
 * The requested ticket.
 */
export const zGetTicketByIdResponse = zTicket;

export const zCreateTicketBody = zCreateTicketRequest;

/**
 * The newly created ticket.
 */
export const zCreateTicketResponse = zTicket;
