// This file is auto-generated by @hey-api/openapi-ts

export interface ClientOptions {
  baseUrl: 'https://software-api/' | (string & {});
}

export interface CatalogCreateModel {
  id?: string;
  vendorId?: string;
  name: string;
  isDeprecated?: boolean;
}

export interface CreateVendorRequestModel {
  name: string;
  url: string;
  pointOfContact: VendorPointOfContactModel;
}

export interface VendorDetailsModel {
  id?: string;
  name: string;
  url: string;
  pointOfContact: VendorPointOfContactModel;
  createdAt?: string;
}

export interface VendorPointOfContactModel {
  name: string;
  email: string;
  phone: string;
}

export interface GetCatalogData {
  body?: never;
  path?: never;
  query?: never;
  url: '/catalog';
}

export interface GetCatalogResponses {
  /**
   * OK
   */
  200: unknown;
}

export interface GetVendorsByVendorIdCatalogItemsData {
  body?: never;
  path: {
    vendorId: string;
  };
  query?: never;
  url: '/vendors/{vendorId}/catalog-items';
}

export interface GetVendorsByVendorIdCatalogItemsResponses {
  /**
   * OK
   */
  200: unknown;
}

export interface PostVendorsByVendorIdCatalogItemsData {
  body: CatalogCreateModel;
  path: {
    vendorId: string;
  };
  query?: never;
  url: '/vendors/{vendorId}/catalog-items';
}

export interface PostVendorsByVendorIdCatalogItemsErrors {
  /**
   * Not Found
   */
  404: string;
}

export type PostVendorsByVendorIdCatalogItemsError =
  PostVendorsByVendorIdCatalogItemsErrors[keyof PostVendorsByVendorIdCatalogItemsErrors];

export interface PostVendorsByVendorIdCatalogItemsResponses {
  /**
   * Created
   */
  201: CatalogCreateModel;
}

export type PostVendorsByVendorIdCatalogItemsResponse =
  PostVendorsByVendorIdCatalogItemsResponses[keyof PostVendorsByVendorIdCatalogItemsResponses];

export interface DeleteVendorsByVendorIdCatalogItemsByItemIdData {
  body?: never;
  path: {
    vendorId: string;
    itemId: string;
  };
  query?: never;
  url: '/vendors/{vendorId}/catalog-items/{itemId}';
}

export interface DeleteVendorsByVendorIdCatalogItemsByItemIdResponses {
  /**
   * OK
   */
  200: unknown;
}

export interface GetVendorsData {
  body?: never;
  path?: never;
  query?: never;
  url: '/vendors';
}

export interface GetVendorsResponses {
  /**
   * OK
   */
  200: VendorDetailsModel[];
}

export type GetVendorsResponse = GetVendorsResponses[keyof GetVendorsResponses];

export interface PostVendorsData {
  body: CreateVendorRequestModel;
  path?: never;
  query?: never;
  url: '/vendors';
}

export interface PostVendorsResponses {
  /**
   * OK
   */
  200: unknown;
}

export interface PutVendorsByIdPointOfContactData {
  body: VendorPointOfContactModel;
  path: {
    id: string;
  };
  query?: never;
  url: '/vendors/{id}/point-of-contact';
}

export interface PutVendorsByIdPointOfContactResponses {
  /**
   * OK
   */
  200: unknown;
}

export interface GetVendorsByIdData {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/vendors/{id}';
}

export interface GetVendorsByIdResponses {
  /**
   * OK
   */
  200: unknown;
}
