// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zCatalogItem = z.object({
  id: z.uuid().optional(),
  vendorId: z.uuid().optional(),
  name: z.string().min(5).max(100),
  isDeprecated: z.boolean().optional(),
});

export const zCatalogCreateItem = z.object({
  vendorId: z.uuid(),
  name: z.string().min(5).max(100),
});

export const zVendorPointOfContactModel = z.object({
  name: z.string().min(3).max(100),
  email: z.string(),
  phone: z.string(),
});

export const zCreateVendorModel = z.object({
  name: z.string().min(3).max(100),
  url: z.string(),
  pointOfContact: zVendorPointOfContactModel,
});

export const zVendorModel = z.object({
  id: z.uuid().optional(),
  name: z.string(),
  url: z.string(),
  pointOfContact: zVendorPointOfContactModel,
  createdAt: z.iso.datetime().optional(),
});

/**
 * OK
 */
export const zGetCatalogResponse = z.array(zCatalogItem);

export const zGetVendorsByVendorIdCatalogItemsPath = z.object({
  vendorId: z.uuid(),
});

export const zPostVendorsByVendorIdCatalogItemsBody = zCatalogCreateItem;

export const zPostVendorsByVendorIdCatalogItemsPath = z.object({
  vendorId: z.uuid(),
});

/**
 * Created
 */
export const zPostVendorsByVendorIdCatalogItemsResponse = zCatalogItem;

export const zDeleteVendorsByVendorIdCatalogItemsByItemIdPath = z.object({
  vendorId: z.uuid(),
  itemId: z.uuid(),
});

/**
 * OK
 */
export const zGetVendorsResponse = z.array(zVendorModel);

export const zPostVendorsBody = zCreateVendorModel;

export const zPutVendorsByIdPointOfContactBody = zVendorPointOfContactModel;

export const zPutVendorsByIdPointOfContactPath = z.object({
  id: z.uuid(),
});

export const zGetVendorsByIdPath = z.object({
  id: z.uuid(),
});

/**
 * OK
 */
export const zGetVendorsByIdResponse = zVendorModel;
