// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zCatalogCreateModel = z.object({
  id: z.uuid().optional(),
  vendorId: z.uuid().optional(),
  name: z.string().min(5).max(100),
  isDeprecated: z.boolean().optional(),
});

export const zVendorPointOfContactModel = z.object({
  name: z.string().min(3).max(100),
  email: z.string(),
  phone: z.string(),
});

export const zCreateVendorRequestModel = z.object({
  name: z.string().min(3).max(100),
  url: z.string(),
  pointOfContact: zVendorPointOfContactModel,
});

export const zVendorDetailsModel = z.object({
  id: z.uuid().optional(),
  name: z.string(),
  url: z.string(),
  pointOfContact: zVendorPointOfContactModel,
  createdAt: z.iso.datetime().optional(),
});

export const zGetVendorsByVendorIdCatalogItemsPath = z.object({
  vendorId: z.uuid(),
});

export const zPostVendorsByVendorIdCatalogItemsBody = zCatalogCreateModel;

export const zPostVendorsByVendorIdCatalogItemsPath = z.object({
  vendorId: z.uuid(),
});

/**
 * Created
 */
export const zPostVendorsByVendorIdCatalogItemsResponse = zCatalogCreateModel;

export const zDeleteVendorsByVendorIdCatalogItemsByItemIdPath = z.object({
  vendorId: z.uuid(),
  itemId: z.uuid(),
});

/**
 * OK
 */
export const zGetVendorsResponse = z.array(zVendorDetailsModel);

export const zPostVendorsBody = zCreateVendorRequestModel;

export const zPutVendorsByIdPointOfContactBody = zVendorPointOfContactModel;

export const zPutVendorsByIdPointOfContactPath = z.object({
  id: z.uuid(),
});

export const zGetVendorsByIdPath = z.object({
  id: z.uuid(),
});
